### ISSUE TITLE
Only seems to work with two default terminals?

### ISSUE THREAD

**Issue by Anupheaus** [NitroGhost/vscode-tabulous#4]
Apologies if I've missed something in the documentation but I can only get two terminals to open when opening vs code?

Here is my config:
```
    "tabulous.defaultTerminals": [
        {
            "name": "Build Lib",
            "directory": "/c/Workspace",
            "command": "blw"
        },
        {
            "name": "Run EC",
            "directory": "/c/Workspace",
            "command": "re"
        },
        {
            "name": "Build EC",
            "directory": "/c/Workspace",
            "command": "bew"
        }
    ]
```

It only seems to be opening and running the last two terminals?

**Comment by NitroGhost** [comment]
you might be running into the same issue that I do from time to time. for some reason, VS Code seems to say it's ready but actually it isn't, meaning that the very first terminal ends up not being created. I usually fix this by closing VS Code then reopen the workspace again.

That said, I'm going to be adding a feature to reload the default terminals so that we don't have to close VS Code just to get them all back again

**Comment by NitroGhost** [comment]
I've refactored the code and added the reload functionality. I've actually changed it so that it waits for the disposing of the lingering terminal to close before it tries to do anything, so hopefully that'll stop the issue of the first tab from being missed. lemme know if the issue still happens 😄
